services:
    db: 
        container_name: mysql_db_crud_app
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: sasa1234
            MYSQL_DATABASE: db_crud_springboot
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        